// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title LabyrinthGovernance
 * @notice DAO Staking & Protocol Revenue Share Contract for Labyrinth V1
 * @dev $LAB stakers earn real yield (ETH/USDC) generated by protocol fees & yield pools.
 */

interface IERC20Token {
    function balanceOf(address account) external view returns (uint256);
    function transfer(address recipient, uint256 amount) external returns (bool);
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
}

contract LabyrinthGovernance {
    address public labToken;
    address public founderAndDevWallet; // Combined X+Y wallet (20%)

    struct Stake {
        uint256 amount;
        uint256 startTime;
        uint256 rewardDebt;
    }

    mapping(address => Stake) public stakes;
    uint256 public totalStaked;
    uint256 public accumulatedYieldPerShare;

    event Staked(address indexed user, uint256 amount);
    event Unstaked(address indexed user, uint256 amount);
    event YieldClaimed(address indexed user, uint256 reward);
    event YieldDistributed(uint256 amount);

    constructor(address _labToken, address _founderAndDevWallet) {
        require(_labToken != address(0), "Invalid LAB token address");
        require(_founderAndDevWallet != address(0), "Invalid founder wallet");
        labToken = _labToken;
        founderAndDevWallet = _founderAndDevWallet;
    }

    function stake(uint256 amount) external {
        require(amount > 0, "Cannot stake 0");
        
        // Claim pending yields if any
        if (stakes[msg.sender].amount > 0) {
            uint256 pending = (stakes[msg.sender].amount * accumulatedYieldPerShare / 1e18) - stakes[msg.sender].rewardDebt;
            if (pending > 0) {
                payable(msg.sender).transfer(pending);
                emit YieldClaimed(msg.sender, pending);
            }
        }

        IERC20Token(labToken).transferFrom(msg.sender, address(this), amount);

        stakes[msg.sender].amount += amount;
        stakes[msg.sender].startTime = block.timestamp;
        stakes[msg.sender].rewardDebt = stakes[msg.sender].amount * accumulatedYieldPerShare / 1e18;

        totalStaked += amount;
        emit Staked(msg.sender, amount);
    }

    function unstake(uint256 amount) external {
        require(stakes[msg.sender].amount >= amount, "Insufficient stake");

        uint256 pending = (stakes[msg.sender].amount * accumulatedYieldPerShare / 1e18) - stakes[msg.sender].rewardDebt;
        if (pending > 0) {
            payable(msg.sender).transfer(pending);
            emit YieldClaimed(msg.sender, pending);
        }

        stakes[msg.sender].amount -= amount;
        stakes[msg.sender].rewardDebt = stakes[msg.sender].amount * accumulatedYieldPerShare / 1e18;
        totalStaked -= amount;

        IERC20Token(labToken).transfer(msg.sender, amount);
        emit Unstaked(msg.sender, amount);
    }

    function distributeYield() external payable {
        require(msg.value > 0, "No yield provided");
        require(totalStaked > 0, "No stakers available");

        // 80% to $LAB Stakers, 20% to Founder & Dev (X+Y)
        uint256 founderShare = (msg.value * 20) / 100;
        uint256 stakerShare = msg.value - founderShare;

        if (founderShare > 0) {
            payable(founderAndDevWallet).transfer(founderShare);
        }

        accumulatedYieldPerShare += (stakerShare * 1e18) / totalStaked;
        emit YieldDistributed(msg.value);
    }

    receive() external payable {}
}
