// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title LabyrinthGovernance
 * @notice DAO Staking & Protocol Revenue Share Contract for Labyrinth V1
 * @dev $LAB stakers earn real yield (ETH/USDC) generated by protocol fees & yield pools.
 *
 * ─── AUDIT FIX LOG ────────────────────────────────────────────────────────────
 * [FIX #3] CRITICAL: Reentrancy vulnerability corrected in stake() and unstake().
 *          Applied the Checks-Effects-Interactions (CEI) pattern:
 *          → rewardDebt is now updated BEFORE any ETH transfer.
 *          → Added a nonReentrant guard modifier for defence-in-depth.
 * ──────────────────────────────────────────────────────────────────────────────
 *
 * ⚠️  DEPLOYMENT STATUS: NOT DEPLOYED ON ANY BLOCKCHAIN NETWORK.
 *     This contract is in local development and audit phase only.
 */

interface IERC20Token {
    function balanceOf(address account) external view returns (uint256);
    function transfer(address recipient, uint256 amount) external returns (bool);
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
}

contract LabyrinthGovernance {

    // ─── [FIX #3] Reentrancy Guard ────────────────────────────────────────────
    uint256 private constant _NOT_ENTERED = 1;
    uint256 private constant _ENTERED     = 2;
    uint256 private _status = _NOT_ENTERED;

    modifier nonReentrant() {
        require(_status != _ENTERED, "LabyrinthGovernance: Reentrant call");
        _status = _ENTERED;
        _;
        _status = _NOT_ENTERED;
    }

    // ─── State Variables ──────────────────────────────────────────────────────
    address public labToken;
    address public founderAndDevWallet; // Combined X+Y wallet (20% revenue share)

    struct Stake {
        uint256 amount;
        uint256 startTime;
        uint256 rewardDebt;
    }

    mapping(address => Stake) public stakes;
    uint256 public totalStaked;
    uint256 public accumulatedYieldPerShare;

    // ─── Events ───────────────────────────────────────────────────────────────
    event Staked(address indexed user, uint256 amount);
    event Unstaked(address indexed user, uint256 amount);
    event YieldClaimed(address indexed user, uint256 reward);
    event YieldDistributed(uint256 amount);

    // ─── Constructor ──────────────────────────────────────────────────────────
    constructor(address _labToken, address _founderAndDevWallet) {
        require(_labToken != address(0),           "LabyrinthGovernance: Invalid LAB token");
        require(_founderAndDevWallet != address(0),"LabyrinthGovernance: Invalid founder wallet");
        labToken            = _labToken;
        founderAndDevWallet = _founderAndDevWallet;
    }

    // ─── Internal Helpers ─────────────────────────────────────────────────────

    /**
     * @dev Calculate pending yield for a staker without any state change.
     */
    function _pendingYield(address user) internal view returns (uint256) {
        Stake storage s = stakes[user];
        if (s.amount == 0) return 0;
        return (s.amount * accumulatedYieldPerShare / 1e18) - s.rewardDebt;
    }

    // ─── Core Staking Functions ───────────────────────────────────────────────

    /**
     * @notice Stake $LAB tokens to earn a share of protocol yield.
     * @param amount Number of $LAB tokens (18-decimal) to stake.
     */
    function stake(uint256 amount) external nonReentrant {
        require(amount > 0, "LabyrinthGovernance: Cannot stake 0");

        // ── CHECKS & EFFECTS (before any external call) ───────────────────────
        uint256 pending = _pendingYield(msg.sender);

        // [FIX #3] Update staker state BEFORE transferring ETH (CEI pattern).
        stakes[msg.sender].amount     += amount;
        stakes[msg.sender].startTime   = block.timestamp;
        stakes[msg.sender].rewardDebt  = stakes[msg.sender].amount * accumulatedYieldPerShare / 1e18;
        totalStaked += amount;

        emit Staked(msg.sender, amount);

        // ── INTERACTIONS ──────────────────────────────────────────────────────
        // Transfer staked $LAB from user to this contract.
        IERC20Token(labToken).transferFrom(msg.sender, address(this), amount);

        // Pay any accrued yield AFTER state is fully updated.
        if (pending > 0) {
            emit YieldClaimed(msg.sender, pending);
            payable(msg.sender).transfer(pending);
        }
    }

    /**
     * @notice Unstake $LAB tokens and collect accrued yield.
     * @param amount Number of $LAB tokens to withdraw.
     */
    function unstake(uint256 amount) external nonReentrant {
        require(stakes[msg.sender].amount >= amount, "LabyrinthGovernance: Insufficient stake");

        // ── CHECKS & EFFECTS (before any external call) ───────────────────────
        uint256 pending = _pendingYield(msg.sender);

        // [FIX #3] Update staker state BEFORE any ETH or token transfer (CEI).
        stakes[msg.sender].amount    -= amount;
        stakes[msg.sender].rewardDebt = stakes[msg.sender].amount * accumulatedYieldPerShare / 1e18;
        totalStaked -= amount;

        // ── INTERACTIONS ──────────────────────────────────────────────────────
        // 1. Return $LAB principal.
        IERC20Token(labToken).transfer(msg.sender, amount);
        emit Unstaked(msg.sender, amount);

        // 2. Pay accrued ETH yield AFTER state is fully updated.
        if (pending > 0) {
            emit YieldClaimed(msg.sender, pending);
            payable(msg.sender).transfer(pending);
        }
    }

    /**
     * @notice Claim yield without unstaking.
     */
    function claimYield() external nonReentrant {
        uint256 pending = _pendingYield(msg.sender);
        require(pending > 0, "LabyrinthGovernance: No yield to claim");

        // [FIX #3] Update rewardDebt BEFORE transferring ETH (CEI).
        stakes[msg.sender].rewardDebt = stakes[msg.sender].amount * accumulatedYieldPerShare / 1e18;

        emit YieldClaimed(msg.sender, pending);
        payable(msg.sender).transfer(pending);
    }

    /**
     * @notice Distribute protocol yield: 80% to $LAB stakers, 20% to Founder & Dev.
     * @dev Called by the protocol revenue router after collecting fees.
     */
    function distributeYield() external payable nonReentrant {
        require(msg.value > 0,       "LabyrinthGovernance: No yield provided");
        require(totalStaked > 0,     "LabyrinthGovernance: No stakers available");

        // 80% to $LAB stakers, 20% to Founder & Dev (X+Y).
        uint256 founderShare = (msg.value * 20) / 100;
        uint256 stakerShare  = msg.value - founderShare;

        // Update accumulated yield per share (scaled by 1e18 for precision).
        accumulatedYieldPerShare += (stakerShare * 1e18) / totalStaked;
        emit YieldDistributed(msg.value);

        // Transfer founder share LAST (interaction after effects).
        if (founderShare > 0) {
            payable(founderAndDevWallet).transfer(founderShare);
        }
    }

    /**
     * @notice View pending yield for any staker address.
     */
    function pendingYield(address user) external view returns (uint256) {
        return _pendingYield(user);
    }

    receive() external payable {}
}
